-- 1
ALTER TABLE VETHANG ADD CONSTRAINT CT_BIENSO UNIQUE(BIENSO);

-- 2
SELECT LG.*
FROM LUOTGUI LG
JOIN VETHANG VT ON VT.MATHE = LG.MATHE
WHERE VT.BIENSO <> LG.BIENSOQUETDUOC

-- 3
SELECT VT.*
FROM VETHANG VT
WHERE DATEDIFF(day, CAST(GETDATE() AS DATE), NGAYHETHAN) BETWEEN 0 AND 3;

-- 4
SELECT TOP 1
       DATEPART(hour, THOIGIANVAO) AS [Giờ],
       COUNT(*) AS [Số lượt vào]
FROM LUOTGUI LG
WHERE DATEPART(month, THOIGIANVAO) = DATEPART(month, GETDATE()) AND DATEPART(year, THOIGIANVAO) = DATEPART(year, GETDATE())
GROUP BY DATEPART(hour, THOIGIANVAO)
ORDER BY COUNT(*) DESC;

-- 5
SELECT CAST(THOIGIANVAO AS DATE) AS [Ngày],
       COUNT(*) AS [Số lượt gửi xe bằng vé lượt]
FROM LUOTGUI LG
WHERE LG.MATHE NOT IN (SELECT MATHE FROM VETHANG)
       AND CAST (THOIGIANVAO AS DATE) = CAST(GETDATE() AS DATE)
GROUP BY CAST(THOIGIANVAO AS DATE);

-- 6
SELECT LG.MATHE,
       COUNT(DISTINCT LG.BIENSOQUETDUOC) AS [Số xe đã sử dụng]
FROM LUOTGUI LG
GROUP BY LG.MATHE
HAVING COUNT(DISTINCT LG.BIENSOQUETDUOC) >= 2;

-- 7
SELECT X.LOAIXE, 
       AVG(DATEDIFF(minute, LG.THOIGIANRA, LG.THOIGIANVAO) / 60.0) AS [Thời gian gửi trung bình]
FROM LUOTGUI LG
JOIN XE X ON LG.BIENSOQUETDUOC = X.BIENSO
WHERE LG.THOIGIANRA IS NOT NULL
GROUP BY X.LOAIXE
HAVING AVG(DATEDIFF(minute, LG.THOIGIANRA, LG.THOIGIANVAO) / 60.0)  >= 6;
GO

-- 8
CREATE TRIGGER TRG_NEW_LG ON LUOTGUI FOR INSERT AS 
BEGIN
       IF EXISTS (
              SELECT 1
              FROM inserted I
              JOIN LUOTGUI LG ON I.BIENSOQUETDUOC = LG.BIENSOQUETDUOC
              WHERE LG.THOIGIANRA IS NULL AND I.MALG <> JG.MALG
       )
       BEGIN 
              ROLLBACK TRANSACTION;
       END
END;
