USE master;
GO
CREATE DATABASE QLDuAn;
GO
USE QLDuAn;
GO

-- 1
ALTER TABLE PHANCONG ADD CONSTRAINT CT_PHANCONG CHECK(SOGIO > 0);

-- 2
SELECT TOP 1 WITH TIES
    NV.MANV, NV.TENNV,
    COUNT(PC.MADA) AS [Số dự án tham gia]
FROM NHANVIEN NV
JOIN PHANCONG PC ON PC.MANV = NV.MANV
GROUP BY NV.MANV, NV.TENNV
ORDER BY COUNT(PC.MADA) DESC;

-- 3
SELECT NV.MANV, NV.TENNV
FROM NHANVIEN NV
WHERE NV.MANV NOT IN (
    SELECT MANV1 FROM XUNGDOT_NHANSU
    UNION
    SELECT MANV2 FROM XUNGDOT_NHANSU
);

-- 4
DELETE FROM DUAN
WHERE MADA NOT IN (SELECT MADA FROM PHANCONG);

-- 5
SELECT DISTINCT
    DA1.MADA AS MADA1,
    DA1.TENDA AS TENDA1,
    DA2.MADA AS MADA2,
    DA2.TENDA AS TENDA2
FROM XUNGDOT_NHANSU XD
JOIN PHANCONG PC1 ON PC1.MANV = XD.MANV1
JOIN PHANCONG PC2 ON PC2.MANV = XD.MANV2
JOIN DUAN DA1 ON DA1.MADA = PC1.MADA
JOIN DUAN DA2 ON DA2.MADA = PC2.MADA
WHERE XD.MUCDO = N'Nghiêm trọng' AND DA1.MADA < DA2.MADA;

-- 6
SELECT DISTINCT
    DA.MADA, DA.TENDA
FROM DUAN DA
JOIN PHANCONG PC ON PC.MADA = DA.MADA
WHERE DA.MADA NOT IN (
    SELECT MADA
    FROM DUAN DA2
    JOIN PHANCONG P2 ON PC2.MADA = DA2.MADA
    WHERE PC2.MANV IN (
        SELECT MANV1 FROM XUNGDOT_NHANSU
        UNION
        SELECT MANV2 FROM XUNGDOT_NHANSU
    )
);

-- 7
SELECT DISTINCT
    XD.MANV1 AS MANV1,
    XD.MANV2 AS MANV2,
    PC1.MADA AS MADA,
    XD.MUCDO AS MUCDO
FROM XUNGDOT_NHANSU XD
JOIN PHANCONG PC1 ON PC1.MANV = XD.MANV1
JOIN PHANCONG PC2 ON PC2.MANV = XD.MANV2
WHERE PC1.MADA = PC2.MADA;
GO

-- 8
CREATE TRIGGER TRG_XD ON XUNGDOT_NHANSU FOR INSERT AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted I
        WHERE I.MANV1 = I.MANV2
    )
    BEGIN
        ROLLBACK TRANSACTION;
    END
END;