USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'QLVanDon')
BEGIN 
    ALTER DATABASE QLVanDon SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLVanDon;
END
GO

CREATE DATABASE QLVanDon
GO

USE QLVanDon
GO

CREATE TABLE KHACHHANG (
    MAKH VARCHAR(10) PRIMARY KEY,
    TENKH NVARCHAR(50) NOT NULL
);

CREATE TABLE TRANGTHAI (
    MATT VARCHAR(10) PRIMARY KEY,
    TENTT NVARCHAR(50) NOT NULL
);

CREATE TABLE VANDON (
    MAVD VARCHAR(10) PRIMARY KEY,
    MAKH VARCHAR(10) NOT NULL,
    NGAYGUI DATE NOT NULL,
    KHOILUONG DECIMAL(18, 2) NOT NULL,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE LICHSU_VANDON (
    MAVD VARCHAR(10) NOT NULL,
    MATT VARCHAR(10) NOT NULL,
    THOIGIAN DATETIME NOT NULL,
    CONSTRAINT PK_LICHSU_VANDON PRIMARY KEY (MAVD, MATT),
    FOREIGN KEY (MAVD) REFERENCES VANDON(MAVD),
    FOREIGN KEY (MATT) REFERENCES TRANGTHAI(MATT)
);
GO

-- 1
ALTER TABLE VANDON ADD CONSTRAINT CT_VD_KL CHECK (KHOILUONG > 0);
GO

-- 2
SELECT VD.MAKH, KH.TENKH, 
    COUNT(*) AS [Số vận đơn]
FROM VANDON VD
JOIN KHACHHANG KH ON KH.MAKH = VD.MAKH
GROUP BY VD.MAKH, KH.TENKH
HAVING COUNT(*) >= 3;
GO

-- 3
SELECT TOP 1
    VD.MAKH, KH.TENKH,
    COUNT (*) AS [Số vận đơn]
FROM VANDON VD
JOIN KHACHHANG KH ON KH.MAKH = VD.MAKH
GROUP BY VD.MAKH, KH.TENKH
ORDER BY COUNT(*) DESC;
GO

-- 4
SELECT L.MAVD, L.MATT, T.TENTT, L.THOIGIAN
FROM LICHSU_VANDON L
JOIN TRANGTHAI T ON L.MATT = T.MATT
WHERE L.THOIGIAN = (
    SELECT MAX(THOIGIAN)
    FROM LICHSU_VANDON L2
    WHERE L2.MAVD = L.MAVD
);

-- 5
SELECT TOP 1
    VD.MAVD, VD.MAKH,
    DATEDIFF(hour, L_NHAN.THOIGIAN, L_GIAO.THOIGIAN) AS [Thời gian giao hàng]
FROM VANDON VD
INNER JOIN LICHSU_VANDON L_NHAN ON L_NHAN.MAVD = VD.MAVD AND L_NHAN.MATT = 'TT01'
INNER JOIN LICHSU_VANDON L_GIAO ON L_GIAO.MAVD = VD.MAVD AND L_GIAO.MATT = 'TT04'
ORDER BY DATEDIFF(hour, L_NHAN.THOIGIAN, L_GIAO.THOIGIAN) ASC;

-- 6
SELECT DATEPART(month, LS_VD.THOIGIAN) AS [Tháng],
    SUM(VD.KHOILUONG) AS [Tổng khối lượng đã giao]
FROM VANDON VD
JOIN LICHSU_VANDON LS_VD ON LS_VD.MAVD = VD.MAVD
WHERE LS_VD.MATT = 'TT04'
GROUP BY 
    DATEPART(year, LS_VD.THOIGIAN),
    DATEPART(month, LS_VD.THOIGIAN);

-- 7
SELECT TOP 1 WITH TIES
    KH.MAKH, KH.TENKH, 
    (1.0 * SUM(DISTINCT CASE WHEN LS_VD.MATT = 'TT05' THEN 1 ELSE 0 END) / COUNT(DISTINCT VD.MAVD)) AS [Tỉ lệ huỷ đơn]
FROM LICHSU_VANDON LS_VD
JOIN VANDON VD ON VD.MAVD = LS_VD.MAVD
JOIN KHACHHANG KH ON KH.MAKH = VD.MAKH
GROUP BY KH.MAKH, KH.TENKH
ORDER BY [Tỉ lệ huỷ đơn] DESC;
GO

-- 8
CREATE TRIGGER TRG_LS_VD_TT ON LICHSU_VANDON FOR INSERT AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted I
        JOIN LICHSU_VANDON ON LS_VD.MAVD = I.MAVD
        WHERE LS_VD.MATT = 'TT05'
            AND I.THOIGIAN > LS_VD.THOIGIAN
    )
    BEGIN
        ROLLBACK TRANSACTION;
    END
END;
GO